os: Visual Studio 2015

platform: x64

environment:
  global:
    MSVC_DEFAULT_OPTIONS: ON
    BOOST_ROOT: C:\Libraries\boost_1_59_0
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib64-msvc-14.0
    MSVC: 1
    MINICONDA: "C:\\Miniconda3-x64"
  matrix:
#    - PYTHON_VERSION: 3.5
#      PYTHON_INSTALL: manual
    - PYTHON_VERSION: 3.6
#      PYTHON_INSTALL: manual
#    - PYTHON_VERSION: 3.5
#      PYTHON_INSTALL: pip
#    - PYTHON_VERSION: 3.6
#      PYTHON_INSTALL: pip

configuration: Release

init:
  - cmd: cmake --version
  - cmd: msbuild /version
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - cmd: git submodule update --init --recursive
  - ps: wget https://bitbucket.org/eigen/eigen/get/1f0f8337c029.zip -OutFile eigen.zip
  - cmd: 7z x eigen.zip -o"C:\projects" -y > nul
  - cmd: rename C:\projects\eigen-eigen-1f0f8337c029 eigen
  - set PATH=%MINICONDA%;%MINICONDA%\Scripts;C:\Program Files (x86)\Pandoc;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-env python=%PYTHON_VERSION% cython numpy pypandoc
  - activate test-env
  - cinst pandoc

before_build:
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -DEIGEN3_INCLUDE_DIR=C:/projects/eigen -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=%configuration% -DENABLE_BOOST=ON -DBOOST_ROOT:PATHNAME="%BOOST_ROOT%" -DBoost_LIBRARY_DIRS:FILEPATH="%BOOST_LIBRARYDIR%" -DBoost_NO_BOOST_CMAKE=TRUE -DBoost_NO_SYSTEM_PATHS=TRUE -DPYTHON=python.exe .. 
  - cmd: set VS90COMNTOOLS=%VS140COMNTOOLS%

build:
  project: C:\projects\dynet\build\dynet.sln
  verbosity: normal

after_build:
#  - if [%PYTHON_INSTALL%]==[manual] (cd C:\projects\dynet\build\python &&
#      python ../../setup.py EIGEN3_INCLUDE_DIR=C:/projects/eigen build --build-dir=.. --skip-build install)
  - cmd: cd C:\projects\dynet\build\python
  - python ../../setup.py EIGEN3_INCLUDE_DIR=C:/projects/eigen build --build-dir=.. --skip-build install
#  - if [%PYTHON_INSTALL%]==[pip] (cd C:\projects\dynet && python setup.py sdist bdist_wheel)

test_script:
#  - cmd: ctest -VV --build-config %configuration% --output-on-failure
#  - if [%PYTHON_INSTALL%]==[pip] (pip install dynet --no-index -f dist)
# Gives mysterious "Command exited with code -1073740791":
#  - python -m unittest discover C:\projects\dynet\tests\python -v

#deploy:
#  - provider: Script
#    on:
#      appveyor_repo_tag: true

#deploy_script:
#  - cmd: cd C:\projects\dynet
#  - ps: cat setup.py | % { $_ -replace "0.0.0", %APPVEYOR_REPO_TAG_NAME% } > setup.py
#  - python setup.py sdist bdist_wheel
#  - python -m pip install -U twine
#  - python -m twine upload --skip-existing dist/*
